apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-web
  template:
    metadata:
      labels:
        app: project-web
    spec:
      containers:
        - name: project-web
          image: ghcr.io/tuneerroy/gpt-code-critic:IMAGE_TAG
          ports:
            - containerPort: 8000
          env:
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: project-secret
                  key: username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-secret
                  key: password
      imagePullSecrets:
        - name: docker-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: project-web
spec:
  selector:
    app: project-web
  ports:
    - port: 8000
---
apiVersion: v1
kind: Secret
metadata:
  name: project-secret
type: kubernetes.io/basic-auth
stringData:
  username: username
  password: password
