[tool.poetry]
name = "web"
version = "0.1.0"
description = ""
authors = ["Jordan Hochman <jhawk111@icloud.com>", "Tuneer Roy <tuneer.roy12@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.95.1"
uvicorn = "^0.21.1"
openai = "^0.27.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
